repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.4  # Use the ref you want to point at
    hooks:
      - id: clang-format
        args: [--style=file] # Other coding style: LLVM, GNU, Chromium, Microsoft, Mozilla, WebKit.