- common_config:
    dtype: (int64)->int32, (float64)->float32
    layout: NCHW

- diopiAdd:
    dtype: (int64)->int32, (float64)->float32
    layout: NCHW

- diopiAddScalar:
    dtype: (int64)->int32, (float64)->float32
    layout: NCHW

- diopiUpsampleNearest:
    layout: NHWC

- diopiUpsampleNearestBackward:
    layout: NHWC

- diopiUpsampleLinear:
    layout: NHWC

- diopiUpsampleLinearBackward:
    layout: NHWC