- common_config:
#     dtype: (int64)->int32, (float64)->float32
    layout: NHWC
    contiguous: False
    
- diopiAdd:
    dtype: (int64)->int32, (float64)->float32
    tensor_dtype: 
        input: (float64)->float32
        other: (float64, int64)->float32
        out: (float64, int64)->float32
    layout: NCHW, NHWC, input(NHWC)
    contiguous: input, out