- common_config:
    dtype: (int64)->int32, (float64)->float32

- diopiAdd:
    dtype: (int64)->int32, (float64)->float32
    layout: NCHW

- diopiAddScalar:
    dtype: (int64)->int32, (float64)->float32
    layout: NCHW